### ISSUE TITLE
JSON Writer shouldn't reference MARC specific stuff

### ISSUE THREAD

**Issue by billdueber** [traject-project/traject#92]
[via @erikhatcher on IRC]

https://github.com/traject-project/traject/blob/master/lib/traject/solr_json_writer.rb#L169-L176

...is too tied to the idea that the only type of source record will be a MARC record. 

This will fail in too many ways if the source record happens to not be MARC. We should probably eliminate the attempt to get an id out of the source record altogether, or else configure it with 
a passed lambda that takes a record and returns an ID, so people can use it with non-MARC sources.

I'd like to approach this by
* first just pulling out the stuff that deals with marc_id and put up a patch release
* check to see if source_record `#respond_to?(:id)` and use that if available.
* Figure out what we want to do about MARC. 
  * One option is to have a settings entry like `provide "logger.get_id_from_record", ->(r) {r["001].value}' that could be injected into the settings when you require a marc reader. 
  * Alternately, we could just monkey-patch MARC::Record to implement an `#id` when you require a MARC reader. 
  * And finally, we could just not worry about it and make people stick the damn id in the context if they want useful id-based error reporting.

**Comment by jrochkind** [comment]
I think it's important to keep focusing on our primary use case: MARC. 

But yes, we should make it work with non-MARC too. 

The idea that I had was that MARC stuff should always be protected by respond_to and such. I thought we had done that, but since it's not tested there are probably omissions. That is exactly what `context.source_record && context.source_record['001'] && context.source_record['001'].value` does.

I don't like the idea of having to configure to get proper debugging and error reporting stuff  -- I definitely do not like the idea of having to make people stick the id in the context themselves -- someitmes an error occurs before that would have happened, of course. 

Are we only talking about error reporting here, anything else?  Error reporting is not a performance issue -- I don't see the problem with MARC-specific error reporting behind a `respond_to` or other guard. We should have a test for a non-MARC input case, to make sure we've done this appropriately. 

What is the problem with this approach?

I am not sure I see a problem with the current approach -- protected by more guards. If there is one, I'd like an actual example, not just a theoretical concern that there should never be any code in there that references MARC. 

When imagining future non-MARC input, I had imagined we'd likely have sub-classes of the Indexer (and/or different mix-ins) that overrode certain things like error reporting.  I still think that's likely, but I'm not saying that's the solution or should be required. If it's actually needed now though, we could provide a MARC-specific sub-class of or mix-in to Indexer with the MARC specific stuff in it, with a base class without it.  We could provide configuration for what Indexer sub-class is used. However, the MARC-specific sub-class should be the _default_ for now, since that is our current use case.

**Comment by jrochkind** [comment]
Since you're talking about a patch release right away, does that mean @erikhatcher actually has a problem that the current code is preventing him from doing? If so, could he be persuaded to file an issue with an explanation and ideally a reproduction?  I want to actually pave the cowpaths, not go off into abstraction for imagined futures.

**Comment by jrochkind** [comment]
Also your Solr unique id is not always "id", I don't want to require this for useful error reporting either. Useful error reporting is hugely important to me, having been an actual barrier with my SolrMarc use. I think source-specific identification is the way to go and important, but fully agree we need to make this possible with non-MARC too. For now, if it gets erikhatcher going, we could even guard that error method with a `kind_of?(Marc::Record)`. (Error reporting in _indexing code_ is not a performance-critical area, it happens rarely and ideally never in a large-scale production run) We can pave the cowpaths better later when we have actual use cases and use. For now we should do the simplest thing that keeps the code simple -- and still providing the best error messages we can by default for our primary MARC use case.

**Comment by billdueber** [comment]
> I think it's important to keep focusing on our primary use case: MARC.

I knew you were going to say that. :-)

First off, we clearly need to guard this (with either a begin/end block or an `is_a?` guard on the source record type), because as it stands now, it'll just plain error our on non-MARC records. I'll do that nowish.

But we should also provide a mechanism for people to be able to report out useful record information on error *regardless* of the data type.

**Comment by jrochkind** [comment]
> But we should also provide a mechanism for people to be able to report out useful record information on error regardless of the data type.

Agreed. But I'd wait until we had an example or two of what people want to do with what types, so our solution is based on actual use cases.
